// Code generated by MockGen. DO NOT EDIT.
// Source: client/client.go

// Package clientmocks is a generated GoMock package.
package clientmocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	client "github.com/pavlovic265/265-gt/client"
)

// MockCliClient is a mock of CliClient interface.
type MockCliClient struct {
	ctrl     *gomock.Controller
	recorder *MockCliClientMockRecorder
}

// MockCliClientMockRecorder is the mock recorder for MockCliClient.
type MockCliClientMockRecorder struct {
	mock *MockCliClient
}

// NewMockCliClient creates a new mock instance.
func NewMockCliClient(ctrl *gomock.Controller) *MockCliClient {
	mock := &MockCliClient{ctrl: ctrl}
	mock.recorder = &MockCliClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCliClient) EXPECT() *MockCliClientMockRecorder {
	return m.recorder
}

// AuthLogin mocks base method.
func (m *MockCliClient) AuthLogin(ctx context.Context, user string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthLogin", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AuthLogin indicates an expected call of AuthLogin.
func (mr *MockCliClientMockRecorder) AuthLogin(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthLogin", reflect.TypeOf((*MockCliClient)(nil).AuthLogin), ctx, user)
}

// AuthLogout mocks base method.
func (m *MockCliClient) AuthLogout(ctx context.Context, user string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthLogout", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AuthLogout indicates an expected call of AuthLogout.
func (mr *MockCliClientMockRecorder) AuthLogout(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthLogout", reflect.TypeOf((*MockCliClient)(nil).AuthLogout), ctx, user)
}

// AuthStatus mocks base method.
func (m *MockCliClient) AuthStatus(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthStatus", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AuthStatus indicates an expected call of AuthStatus.
func (mr *MockCliClientMockRecorder) AuthStatus(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthStatus", reflect.TypeOf((*MockCliClient)(nil).AuthStatus), ctx)
}

// CreatePullRequest mocks base method.
func (m *MockCliClient) CreatePullRequest(ctx context.Context, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePullRequest", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePullRequest indicates an expected call of CreatePullRequest.
func (mr *MockCliClientMockRecorder) CreatePullRequest(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePullRequest", reflect.TypeOf((*MockCliClient)(nil).CreatePullRequest), ctx, args)
}

// HasOpenPullRequestForBranch mocks base method.
func (m *MockCliClient) HasOpenPullRequestForBranch(ctx context.Context, branch string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasOpenPullRequestForBranch", ctx, branch)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasOpenPullRequestForBranch indicates an expected call of HasOpenPullRequestForBranch.
func (mr *MockCliClientMockRecorder) HasOpenPullRequestForBranch(ctx, branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasOpenPullRequestForBranch", reflect.TypeOf((*MockCliClient)(nil).HasOpenPullRequestForBranch), ctx, branch)
}

// ListPullRequests mocks base method.
func (m *MockCliClient) ListPullRequests(ctx context.Context, args []string) ([]client.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPullRequests", ctx, args)
	ret0, _ := ret[0].([]client.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPullRequests indicates an expected call of ListPullRequests.
func (mr *MockCliClientMockRecorder) ListPullRequests(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPullRequests", reflect.TypeOf((*MockCliClient)(nil).ListPullRequests), ctx, args)
}

// MergePullRequest mocks base method.
func (m *MockCliClient) MergePullRequest(ctx context.Context, prNumber int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePullRequest", ctx, prNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergePullRequest indicates an expected call of MergePullRequest.
func (mr *MockCliClientMockRecorder) MergePullRequest(ctx, prNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePullRequest", reflect.TypeOf((*MockCliClient)(nil).MergePullRequest), ctx, prNumber)
}

// UpdatePullRequestBaseBranch mocks base method.
func (m *MockCliClient) UpdatePullRequestBaseBranch(ctx context.Context, branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePullRequestBaseBranch", ctx, branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePullRequestBaseBranch indicates an expected call of UpdatePullRequestBaseBranch.
func (mr *MockCliClientMockRecorder) UpdatePullRequestBaseBranch(ctx, branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePullRequestBaseBranch", reflect.TypeOf((*MockCliClient)(nil).UpdatePullRequestBaseBranch), ctx, branch)
}
