// Code generated by MockGen. DO NOT EDIT.
// Source: helpers/git_helper.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGitHelper is a mock of GitHelper interface.
type MockGitHelper struct {
	ctrl     *gomock.Controller
	recorder *MockGitHelperMockRecorder
}

// MockGitHelperMockRecorder is the mock recorder for MockGitHelper.
type MockGitHelperMockRecorder struct {
	mock *MockGitHelper
}

// NewMockGitHelper creates a new mock instance.
func NewMockGitHelper(ctrl *gomock.Controller) *MockGitHelper {
	mock := &MockGitHelper{ctrl: ctrl}
	mock.recorder = &MockGitHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHelper) EXPECT() *MockGitHelperMockRecorder {
	return m.recorder
}

// CheckGTVersion mocks base method.
func (m *MockGitHelper) CheckGTVersion() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckGTVersion")
}

// CheckGTVersion indicates an expected call of CheckGTVersion.
func (mr *MockGitHelperMockRecorder) CheckGTVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckGTVersion", reflect.TypeOf((*MockGitHelper)(nil).CheckGTVersion))
}

// DeleteChildren mocks base method.
func (m *MockGitHelper) DeleteChildren(branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChildren", branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChildren indicates an expected call of DeleteChildren.
func (mr *MockGitHelperMockRecorder) DeleteChildren(branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChildren", reflect.TypeOf((*MockGitHelper)(nil).DeleteChildren), branch)
}

// DeleteFromParentChildren mocks base method.
func (m *MockGitHelper) DeleteFromParentChildren(parent, branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFromParentChildren", parent, branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFromParentChildren indicates an expected call of DeleteFromParentChildren.
func (mr *MockGitHelperMockRecorder) DeleteFromParentChildren(parent, branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFromParentChildren", reflect.TypeOf((*MockGitHelper)(nil).DeleteFromParentChildren), parent, branch)
}

// DeleteParent mocks base method.
func (m *MockGitHelper) DeleteParent(branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteParent", branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteParent indicates an expected call of DeleteParent.
func (mr *MockGitHelperMockRecorder) DeleteParent(branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteParent", reflect.TypeOf((*MockGitHelper)(nil).DeleteParent), branch)
}

// EnsureGitRepository mocks base method.
func (m *MockGitHelper) EnsureGitRepository() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureGitRepository")
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureGitRepository indicates an expected call of EnsureGitRepository.
func (mr *MockGitHelperMockRecorder) EnsureGitRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureGitRepository", reflect.TypeOf((*MockGitHelper)(nil).EnsureGitRepository))
}

// GetBranches mocks base method.
func (m *MockGitHelper) GetBranches() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBranches")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBranches indicates an expected call of GetBranches.
func (mr *MockGitHelperMockRecorder) GetBranches() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBranches", reflect.TypeOf((*MockGitHelper)(nil).GetBranches))
}

// GetChildren mocks base method.
func (m *MockGitHelper) GetChildren(branch string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildren", branch)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetChildren indicates an expected call of GetChildren.
func (mr *MockGitHelperMockRecorder) GetChildren(branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildren", reflect.TypeOf((*MockGitHelper)(nil).GetChildren), branch)
}

// GetCurrentBranchName mocks base method.
func (m *MockGitHelper) GetCurrentBranchName() (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentBranchName")
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentBranchName indicates an expected call of GetCurrentBranchName.
func (mr *MockGitHelperMockRecorder) GetCurrentBranchName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentBranchName", reflect.TypeOf((*MockGitHelper)(nil).GetCurrentBranchName))
}

// GetGitRoot mocks base method.
func (m *MockGitHelper) GetGitRoot() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGitRoot")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGitRoot indicates an expected call of GetGitRoot.
func (mr *MockGitHelperMockRecorder) GetGitRoot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGitRoot", reflect.TypeOf((*MockGitHelper)(nil).GetGitRoot))
}

// GetParent mocks base method.
func (m *MockGitHelper) GetParent(branch string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParent", branch)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetParent indicates an expected call of GetParent.
func (mr *MockGitHelperMockRecorder) GetParent(branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParent", reflect.TypeOf((*MockGitHelper)(nil).GetParent), branch)
}

// IsGitRepository mocks base method.
func (m *MockGitHelper) IsGitRepository() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsGitRepository")
	ret0, _ := ret[0].(error)
	return ret0
}

// IsGitRepository indicates an expected call of IsGitRepository.
func (mr *MockGitHelperMockRecorder) IsGitRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsGitRepository", reflect.TypeOf((*MockGitHelper)(nil).IsGitRepository))
}

// IsProtectedBranch mocks base method.
func (m *MockGitHelper) IsProtectedBranch(branch string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProtectedBranch", branch)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsProtectedBranch indicates an expected call of IsProtectedBranch.
func (mr *MockGitHelperMockRecorder) IsProtectedBranch(branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProtectedBranch", reflect.TypeOf((*MockGitHelper)(nil).IsProtectedBranch), branch)
}

// RelinkParentChildren mocks base method.
func (m *MockGitHelper) RelinkParentChildren(parent, parentChildren, branch, branchChildren string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelinkParentChildren", parent, parentChildren, branch, branchChildren)
	ret0, _ := ret[0].(error)
	return ret0
}

// RelinkParentChildren indicates an expected call of RelinkParentChildren.
func (mr *MockGitHelperMockRecorder) RelinkParentChildren(parent, parentChildren, branch, branchChildren interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelinkParentChildren", reflect.TypeOf((*MockGitHelper)(nil).RelinkParentChildren), parent, parentChildren, branch, branchChildren)
}

// SetChildren mocks base method.
func (m *MockGitHelper) SetChildren(parent, children string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetChildren", parent, children)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetChildren indicates an expected call of SetChildren.
func (mr *MockGitHelperMockRecorder) SetChildren(parent, children interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetChildren", reflect.TypeOf((*MockGitHelper)(nil).SetChildren), parent, children)
}

// SetParent mocks base method.
func (m *MockGitHelper) SetParent(parent, child string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetParent", parent, child)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetParent indicates an expected call of SetParent.
func (mr *MockGitHelperMockRecorder) SetParent(parent, child interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetParent", reflect.TypeOf((*MockGitHelper)(nil).SetParent), parent, child)
}

// UnmarshalChildren mocks base method.
func (m *MockGitHelper) UnmarshalChildren(children string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalChildren", children)
	ret0, _ := ret[0].([]string)
	return ret0
}

// UnmarshalChildren indicates an expected call of UnmarshalChildren.
func (mr *MockGitHelperMockRecorder) UnmarshalChildren(children interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalChildren", reflect.TypeOf((*MockGitHelper)(nil).UnmarshalChildren), children)
}
