// Code generated by MockGen. DO NOT EDIT.
// Source: helpers/git_helper.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	constants "github.com/pavlovic265/265-gt/constants"
)

// MockGitHelper is a mock of GitHelper interface.
type MockGitHelper struct {
	ctrl     *gomock.Controller
	recorder *MockGitHelperMockRecorder
}

// MockGitHelperMockRecorder is the mock recorder for MockGitHelper.
type MockGitHelperMockRecorder struct {
	mock *MockGitHelper
}

// NewMockGitHelper creates a new mock instance.
func NewMockGitHelper(ctrl *gomock.Controller) *MockGitHelper {
	mock := &MockGitHelper{ctrl: ctrl}
	mock.recorder = &MockGitHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHelper) EXPECT() *MockGitHelperMockRecorder {
	return m.recorder
}

// DeleteParent mocks base method.
func (m *MockGitHelper) DeleteParent(branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteParent", branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteParent indicates an expected call of DeleteParent.
func (mr *MockGitHelperMockRecorder) DeleteParent(branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteParent", reflect.TypeOf((*MockGitHelper)(nil).DeleteParent), branch)
}

// DeletePending mocks base method.
func (m *MockGitHelper) DeletePending(branchType constants.Branch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePending", branchType)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePending indicates an expected call of DeletePending.
func (mr *MockGitHelperMockRecorder) DeletePending(branchType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePending", reflect.TypeOf((*MockGitHelper)(nil).DeletePending), branchType)
}

// EnsureGitRepository mocks base method.
func (m *MockGitHelper) EnsureGitRepository() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureGitRepository")
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureGitRepository indicates an expected call of EnsureGitRepository.
func (mr *MockGitHelperMockRecorder) EnsureGitRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureGitRepository", reflect.TypeOf((*MockGitHelper)(nil).EnsureGitRepository))
}

// GetBranches mocks base method.
func (m *MockGitHelper) GetBranches() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBranches")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBranches indicates an expected call of GetBranches.
func (mr *MockGitHelperMockRecorder) GetBranches() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBranches", reflect.TypeOf((*MockGitHelper)(nil).GetBranches))
}

// GetRemoteBranches mocks base method.
func (m *MockGitHelper) GetRemoteBranches() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteBranches")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemoteBranches indicates an expected call of GetRemoteBranches.
func (mr *MockGitHelperMockRecorder) GetRemoteBranches() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteBranches", reflect.TypeOf((*MockGitHelper)(nil).GetRemoteBranches))
}

// GetChildren mocks base method.
func (m *MockGitHelper) GetChildren(branch string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildren", branch)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetChildren indicates an expected call of GetChildren.
func (mr *MockGitHelperMockRecorder) GetChildren(branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildren", reflect.TypeOf((*MockGitHelper)(nil).GetChildren), branch)
}

// GetCurrentBranch mocks base method.
func (m *MockGitHelper) GetCurrentBranch() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentBranch")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentBranch indicates an expected call of GetCurrentBranch.
func (mr *MockGitHelperMockRecorder) GetCurrentBranch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentBranch", reflect.TypeOf((*MockGitHelper)(nil).GetCurrentBranch))
}

// GetGitRoot mocks base method.
func (m *MockGitHelper) GetGitRoot() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGitRoot")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGitRoot indicates an expected call of GetGitRoot.
func (mr *MockGitHelperMockRecorder) GetGitRoot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGitRoot", reflect.TypeOf((*MockGitHelper)(nil).GetGitRoot))
}

// GetParent mocks base method.
func (m *MockGitHelper) GetParent(branch string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParent", branch)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParent indicates an expected call of GetParent.
func (mr *MockGitHelperMockRecorder) GetParent(branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParent", reflect.TypeOf((*MockGitHelper)(nil).GetParent), branch)
}

// GetPending mocks base method.
func (m *MockGitHelper) GetPending(branchType constants.Branch) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPending", branchType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPending indicates an expected call of GetPending.
func (mr *MockGitHelperMockRecorder) GetPending(branchType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPending", reflect.TypeOf((*MockGitHelper)(nil).GetPending), branchType)
}

// GetRemoteURL mocks base method.
func (m *MockGitHelper) GetRemoteURL(remoteName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteURL", remoteName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemoteURL indicates an expected call of GetRemoteURL.
func (mr *MockGitHelperMockRecorder) GetRemoteURL(remoteName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteURL", reflect.TypeOf((*MockGitHelper)(nil).GetRemoteURL), remoteName)
}

// IsGitRepository mocks base method.
func (m *MockGitHelper) IsGitRepository() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsGitRepository")
	ret0, _ := ret[0].(error)
	return ret0
}

// IsGitRepository indicates an expected call of IsGitRepository.
func (mr *MockGitHelperMockRecorder) IsGitRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsGitRepository", reflect.TypeOf((*MockGitHelper)(nil).IsGitRepository))
}

// IsProtectedBranch mocks base method.
func (m *MockGitHelper) IsProtectedBranch(ctx context.Context, branch string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProtectedBranch", ctx, branch)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsProtectedBranch indicates an expected call of IsProtectedBranch.
func (mr *MockGitHelperMockRecorder) IsProtectedBranch(ctx, branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProtectedBranch", reflect.TypeOf((*MockGitHelper)(nil).IsProtectedBranch), ctx, branch)
}

// IsRebaseInProgress mocks base method.
func (m *MockGitHelper) IsRebaseInProgress() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRebaseInProgress")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRebaseInProgress indicates an expected call of IsRebaseInProgress.
func (mr *MockGitHelperMockRecorder) IsRebaseInProgress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRebaseInProgress", reflect.TypeOf((*MockGitHelper)(nil).IsRebaseInProgress))
}

// RebaseBranch mocks base method.
func (m *MockGitHelper) RebaseBranch(branch, parent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebaseBranch", branch, parent)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebaseBranch indicates an expected call of RebaseBranch.
func (mr *MockGitHelperMockRecorder) RebaseBranch(branch, parent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebaseBranch", reflect.TypeOf((*MockGitHelper)(nil).RebaseBranch), branch, parent)
}

// RelinkParentChildren mocks base method.
func (m *MockGitHelper) RelinkParentChildren(parent string, branchChildren []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelinkParentChildren", parent, branchChildren)
	ret0, _ := ret[0].(error)
	return ret0
}

// RelinkParentChildren indicates an expected call of RelinkParentChildren.
func (mr *MockGitHelperMockRecorder) RelinkParentChildren(parent, branchChildren interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelinkParentChildren", reflect.TypeOf((*MockGitHelper)(nil).RelinkParentChildren), parent, branchChildren)
}

// SetParent mocks base method.
func (m *MockGitHelper) SetParent(parent, child string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetParent", parent, child)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetParent indicates an expected call of SetParent.
func (mr *MockGitHelperMockRecorder) SetParent(parent, child interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetParent", reflect.TypeOf((*MockGitHelper)(nil).SetParent), parent, child)
}

// SetPending mocks base method.
func (m *MockGitHelper) SetPending(branchType constants.Branch, branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPending", branchType, branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPending indicates an expected call of SetPending.
func (mr *MockGitHelperMockRecorder) SetPending(branchType, branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPending", reflect.TypeOf((*MockGitHelper)(nil).SetPending), branchType, branch)
}

// ValidateBranchName mocks base method.
func (m *MockGitHelper) ValidateBranchName(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateBranchName", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateBranchName indicates an expected call of ValidateBranchName.
func (mr *MockGitHelperMockRecorder) ValidateBranchName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateBranchName", reflect.TypeOf((*MockGitHelper)(nil).ValidateBranchName), name)
}
