// Code generated by MockGen. DO NOT EDIT.
// Source: config/config.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	config "github.com/pavlovic265/265-gt/config"
)

// MockConfigManager is a mock of ConfigManager interface.
type MockConfigManager struct {
	ctrl     *gomock.Controller
	recorder *MockConfigManagerMockRecorder
}

// MockConfigManagerMockRecorder is the mock recorder for MockConfigManager.
type MockConfigManagerMockRecorder struct {
	mock *MockConfigManager
}

// NewMockConfigManager creates a new mock instance.
func NewMockConfigManager(ctrl *gomock.Controller) *MockConfigManager {
	mock := &MockConfigManager{ctrl: ctrl}
	mock.recorder = &MockConfigManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigManager) EXPECT() *MockConfigManagerMockRecorder {
	return m.recorder
}

// LoadGlobalConfig mocks base method.
func (m *MockConfigManager) LoadGlobalConfig() (*config.GlobalConfigStruct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadGlobalConfig")
	ret0, _ := ret[0].(*config.GlobalConfigStruct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadGlobalConfig indicates an expected call of LoadGlobalConfig.
func (mr *MockConfigManagerMockRecorder) LoadGlobalConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadGlobalConfig", reflect.TypeOf((*MockConfigManager)(nil).LoadGlobalConfig))
}

// LoadLocalConfig mocks base method.
func (m *MockConfigManager) LoadLocalConfig() (*config.LocalConfigStruct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadLocalConfig")
	ret0, _ := ret[0].(*config.LocalConfigStruct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadLocalConfig indicates an expected call of LoadLocalConfig.
func (mr *MockConfigManagerMockRecorder) LoadLocalConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadLocalConfig", reflect.TypeOf((*MockConfigManager)(nil).LoadLocalConfig))
}

// SaveGlobalConfig mocks base method.
func (m *MockConfigManager) SaveGlobalConfig(configToSave config.GlobalConfigStruct) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveGlobalConfig", configToSave)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveGlobalConfig indicates an expected call of SaveGlobalConfig.
func (mr *MockConfigManagerMockRecorder) SaveGlobalConfig(configToSave interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveGlobalConfig", reflect.TypeOf((*MockConfigManager)(nil).SaveGlobalConfig), configToSave)
}

// SaveLocalConfig mocks base method.
func (m *MockConfigManager) SaveLocalConfig(configToSave config.LocalConfigStruct) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLocalConfig", configToSave)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLocalConfig indicates an expected call of SaveLocalConfig.
func (mr *MockConfigManagerMockRecorder) SaveLocalConfig(configToSave interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLocalConfig", reflect.TypeOf((*MockConfigManager)(nil).SaveLocalConfig), configToSave)
}
