name: Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-lint-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-lint-go-
          
    - name: Download dependencies
      run: go mod download
      
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.4.0
        
    - name: Add golangci-lint to PATH
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      
    - name: Run golangci-lint
      run: make lint
      
    - name: Check for linting issues
      run: |
        if make lint; then
          echo "✅ Linting passed - no issues found"
        else
          echo "❌ Linting failed - issues found"
          exit 1
        fi
